version: "3.9"

networks:
  homelabz:
    external: true

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: homelabdb
    volumes:
      - ./dbs/volumes/postgres:/var/lib/postgresql/data
    networks:
      - homelabz

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./cloud/data:/var/www/html
    environment:
      POSTGRES_DB: homelabdb
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: senha123
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - homelabz


  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"
    volumes:
      - ./media/config:/config
      - ./media/library:/library
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - homelabz

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/portainer_data:/data
    networks:
      - homelabz
