# media/docker-compose.yml
version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./library:/library
    environment:
      - TZ=America/Sao_Paulo
networks:
  default:
    external:
      name: homelabz
