# dbs/docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=homelabdb
      - POSTGRES_USER=homelab
      - POSTGRES_PASSWORD=senha123
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - homelabz


networks:
  default:
    external:
      name: homelabz

